### ISSUE TITLE
What dependencies are neede to build?

### ISSUE THREAD

**Issue by nemya9066** [corporateshark/PortAMP#7]
Does the project need dependencies to build cause I'm getting this cmake error when trying to build.
>CMake Error at CMakeLists.txt:135 (set_property):
> set_property could not find TARGET libvorbis.  Perhaps it has not yet been created.

even though I have the package libvorbis installed on my system which is arch linux btw I followed the exact instruction listed any help?

**Comment by corporateshark** [comment]
Everything you need to compile the project is in the `libs` folder. If it does not work on Linux out of the box, check how the `elseif(APPLE)` part of `CMakeLists.txt` is implemented.

**Comment by nemya9066** [comment]
thanks for putting me in the right direction I don't have experience with cmake always just used regular make anyway needed to add this 4 line to the else part in the CMakeLists.txt
>add_subdirectory(libs/flac-1.3.3 EXCLUDE_FROM_ALL)
>add_subdirectory(libs/libogg-1.3.2 EXCLUDE_FROM_ALL)
>add_subdirectory(libs/libvorbis-1.3.5 EXCLUDE_FROM_ALL)
>add_subdirectory(libs/libmodplug-0.8.8.5 EXCLUDE_FROM_ALL)

But that wasn't enough the compilation had some problem too(maybe because I'm on Linux?) I needed to add these lines to these files:
>iWaveDataEncoder.h ++ #include  cstdint
>WAVDataEncoder.h ++ #include cstring ++ #include cstring

Just one last question you mention the player being portable but for me it was dynamically linked with a bunch of libraries so it need those installed to play whatever file depends on them that's normal right?

**Comment by sergeevabc** [comment]
Dear @corporateshark, could you be so kind to compile a binary suitable for Windows 7 x64? I'm a user, not a developer, so this task looks quite complicated to me.

**Comment by corporateshark** [comment]
@sergeevabc added https://github.com/corporateshark/PortAMP/releases/tag/release-1.2.2

**Comment by sergeevabc** [comment]
@corporateshark Thank you, but it does not work on my end.

``` console
$ portamp.exe
PortAMP version 1.2.2 (Mar 15 2024 20:55:22 via Microsoft Visual C++ for Win64)
Copyright (C) 2015-2024 Sergey Kosarevsky
portamp@linderdaum.com
https://github.com/corporateshark/PortAMP

portamp <filename1> [<filename2> ...] [--loop] [--wav-modplug] [--verbose] [--output-file <filename.wav>]

$ portamp.exe in.mp3
Unable to load OpenAL32.dll or soft_oal.dll
```

![2024-0513-0625 portamp 122 error](https://github.com/corporateshark/PortAMP/assets/373718/74b5cb3d-c588-41c4-9eb9-7ac4da95f0d1)

**Comment by corporateshark** [comment]
You need to install https://www.openal-soft.org or just build it and put `soft_oal.dll` into the PortAMP folder next to the `.exe` file.

**Comment by sergeevabc** [comment]
I can hear the sound now…

``` console
$ portamp.exe --verbose in.mp3

OpenAL version : 1.1 ALSOFT 1.23.1
OpenAL vendor  : OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL extensions:
EAX EAX2.0 EAX3.0 EAX4.0 EAX5.0 EAX-RAM AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STATIC_BUFFER AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_bformat_ex AL_SOFTX_bformat_hoa AL_SOFT_block_alignment AL_SOFT_buffer_length_query AL_SOFT_callback_buffer AL_SOFTX_convolution_reverb AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_direct_channels_remix AL_SOFT_effect_target AL_SOFT_events AL_SOFT_gain_clamp_ex AL_SOFTX_hold_on_disconnect AL_SOFT_loop_points AL_SOFTX_map_buffer AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize AL_SOFT_source_start_delay AL_SOFT_UHJ AL_SOFT_UHJ_ex

Opening in.mp3
```

…but when I press any key, I see the following error.

``` console
Opening in.mp3

terminate called without an active exception

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

![2024-0513-0625 portamp 122 error](https://github.com/corporateshark/PortAMP/assets/373718/74b5cb3d-c588-41c4-9eb9-7ac4da95f0d1)

**Comment by corporateshark** [comment]
Can you run it under a debugger to get a crash callstack?

**Comment by sergeevabc** [comment]
Err, I don't know what is a callstack, but I can follow instructions if you provide them.
